[package]
name = "crab-iot"
version = "0.1.0"
authors = ["Arturo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
debug = true
lto = true
codegen-units = 1

[dependencies]
device = {path = "./device"}
warp = "0.2"
tokio = { version = "0.2", features = ["full"] }
serde_json = "1.0"
reqwest = { version = "0.10", features = ["blocking", "json"] }

[workspace]
members = ["fake_plugin", "bench", "device"]
