[package]
name = "crab-iot"
version = "0.1.0"
authors = ["Arturo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"
libloading = "0.6"
once_cell = "1.4"
reqwest = { version = "0.10", features = ["blocking", "json"] }
[dependencies.rusqlite]
version = "0.24.1"
features = ["bundled"]
