version: 2.1

jobs:
    test:
        docker:
            - image: arturocs/crab-iot:latest
        steps:
            - checkout
            - run: make test

workflows:
    test_in_docker:
        jobs:
            - test
