name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --workspace
    - name: Run tests
      run: cargo test --verbose
    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1.0.7
    - name: rust-rustfmt-check
      uses: mbrobbel/rustfmt-check@0.3.0


